[cmd]
Start = """Приветствую, юзер!👋
Я - бот 🤖, запрограммированный скачивать музыку из SoundCloud.
Отправь мне ссылку на [soundcloud.com] и я отвечу прикрепленным аудио-файлом

Канал обновлений: @sc_download_bot_info_ru"""

Help = """Отправьте мне ссылку на песню, и я загружу её сюда.
Если в процессе возникают ошибки - сперва убедитесь что ссылка рабочая, а сама песня доступная.
После этого, попробуйте отправить сообщение еще раз. \
Если ошибка осталась - свяжитесь с разработчиком (@Camelva)

= Канал обновлений: @sc_download_bot_info_ru
= На данный момент поддерживаются только прямые ссылки на песни из [soundcloud.com]

Если вам нравится моя работа и хотите помочь - \
пожалуйста, <a href="https://www.patreon.com/camelva">поддержите меня на Patreon</a> \
или напрямую с помощью BTC: <code>1EmHYR8kZsuALW2XyVRKYLXNKqZ95hc7YP</code>"""

Default = """Хмм, я не знаю такой команды.
Посмотрите в /help для дополнительной информации"""

[process]
Start = """Ждите, проверяю доступна ли эта песня.. 🌪"""

Queue = """Обрабатываю предыдущие ваши песни.."""

Fetching = """Достаю песню из soundcloud-а.."""

Uploading = """Все готово. Загружаю песню в чат.."""

[err]
NotURL = """Я не могу найти ссылку в вашем сообщении 👀.
Если в сообщении есть другой текст - попробуйте удалить всё лишнее и отправить сообщение ещё раз"""

NotSoundCloudURL = """Не похоже чтобы эта ссылка вела на [soundcloud.com]. 👀
Если в сообщении есть другой текст - попробуйте удалить всё лишнее и отправить сообщение ещё раз"""

UnsupportedFormat = """Я еще не умею работать с плейлистами и другими форматами"""

UnsupportedService = """Этот сервис не поддерживается"""

UnavailableSong = """Похоже что это песня недоступна для бота.
Скорее всего, из-за региональных ограничений, и на данный момент я не могу это обойти"""

SizeLimit = """Похоже что этот файл весит слишком много.
Телеграм ограничивает размер загружаемых файлов ботами до 50мб и я не могу обойти это ограничение."""

Default = """Хмм, с этой песней какая-то неизвестная ошибка 🤔.
Попробуйте снова либо же свяжитесь с автором.

Текст ошибки: {{.errMessage}}"""
