[cmd]
Start = """Hello, user!👋
I'm SoundCloud downloader bot.
Send me an url from [soundcloud.com] and i will respond with attached audio file

Updates channel: @sc_download_bot_info"""

Help = """Send me an url and i will download it for you.
If something went wrong - first make sure url is valid and song available.
Then try send message again. \
If error still persist - contact with developer (@Camelva)

= Updates channel: @sc_download_bot_info
= Currently supported only direct song links from [soundcloud.com]

If you appreciate my work and wish to help - \
please consider to <a href="https://www.patreon.com/camelva">support me on Patreon</a> \
or directly with BTC: <code>1EmHYR8kZsuALW2XyVRKYLXNKqZ95hc7YP</code>"""

Default = """I don't know that command.
Use /help for additional info"""

[process]
Start = """Please wait, checking song availability.."""

Queue = """Processing your previous songs.."""

Fetching = """Fetching song from soundcloud.."""

Uploading = """Everything done. Uploading song to you.."""

Storage = """This file's size is breaking telegram's limit. Trying to upload to external storage.."""

StorageReady = """Your song is ready. It will be available to download for 10 days:

- {{.link}}
"""

[err]
NotURL = """I can't find any link in your message. 👀
If there is some other text - try to remove everything else and send message again"""

NotSoundCloudURL = """This link does not seem to lead to [soundcloud.com]. 👀
If there is some other text - try to remove everything else and send message again"""

UnsupportedFormat = """I do not know how to work with playlists and other formats yet"""

UnsupportedService = """This service unsupported yet."""

UnavailableSong = """Seems like this song is unavailable for bot.
Most likely because of regional restrictions and i can't bypass it by now"""

SizeLimit = """Looks like this song weighs too much.
Telegram limits uploading files size to 50mb and we can't avoid this limit."""

Default = """There is some undefined error with this song 🤔.
Please try again or contact with developer.

Error text: {{.errMessage}}"""

[util]
GetCover = """Download cover"""