[cmd]
Start = """\
Приветствую, юзер!👋
Я - бот 🤖, скачивающий музыку из SoundCloud.
Отправь мне ссылку на [soundcloud.com] и я отвечу прикреплённым аудио-файлом

Бот работает автоматически в личных сообщениях и каналах, \
в группах же необходимо начинать загрузку с отправки команды /get

Канал обновлений: @scdl_info\
"""

Help = """\
Отправь мне ссылку на песню, и я загружу её сюда.
Если в процессе возникают ошибки - сперва убедитесь что ссылка рабочая, а сама песня доступна.
После этого, попробуйте отправить сообщение еще раз. \
Если ошибка осталась - свяжитесь со мной (@Camelva)

= Канал обновлений: @scdl_info
= На данный момент поддерживаются только прямые ссылки на песни из [soundcloud.com]

Если вам нравится моя работа и хотите помочь - \
поддержите меня донатом. Узнать больше - /donate\
"""

Get = "Хорошо, теперь отправь мне ссылку"

Donate = """\
<i>Каждый донат помогает мне продолжать поддерживать мои проекты и улучшать их</i>

У меня есть страница на <a href="https://www.patreon.com/camelva">Patreon</a>, \
где поддерживаются большинство методов оплаты.
Для дополнительных методов - смотрите на <a href="https://camelva.pp.ua/donate.html">Веб-странице</a>.

Если вы хотите использовать нечто другое - свяжитесь со мной (@Camelva)\
"""

Default = """\
Хмм, я не знаю такой команды.
Посмотрите в /help для дополнительной информации\
"""

[process]
Start = "Проверяю ссылку.."

Fetching = "Скачиваю песню из soundcloud-а.."

Uploading = "Все готово. Загружаю песню в чат.."

Ready = """[ \
<a href="{{.cover}}">Обложка</a> \
| \
<a href="{{.source}}">Источник</a> \
]

@scdl_info\
"""

Storage = """\
Размер этого файла превышает лимит телеграма.
Загружаю на внешнее хранилище..\
"""

StorageReady = """\
Ваша песня готова. Она будет доступна для загрузки на протяжении 10 дней:

{{.link}}\
"""

[err]
NotURL = """\
Я не могу найти ссылку в вашем сообщении 👀.
Если в сообщении есть другой текст - попробуйте удалить всё лишнее и отправить сообщение ещё раз\
"""

NotSoundCloudURL = """\
Не похоже чтобы эта ссылка вела на [soundcloud.com]. 👀
Если в сообщении есть другой текст - попробуйте удалить всё лишнее и отправить сообщение ещё раз\
"""

UnsupportedFormat = "Я еще не умею работать с плейлистами и другими форматами"

UnavailableSong = """\
Похоже что это песня недоступна для бота.
Скорее всего, из-за региональных ограничений, и на данный момент я не могу это обойти\
"""

Internal = """\
Внутренняя ошибка, повторите попытку позже.

Ошибка: <code>{{.errMessage}}</code>\
"""

Default = """\
Хмм, с этой песней какая-то неизвестная ошибка 🤔.
Попробуйте снова либо же свяжитесь с автором.

Текст ошибки: {{.errMessage}}\
"""